{% set name = "yargy" %}
{% set version = "0.15.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yargy-{{ version }}.tar.gz
  sha256: 3cdc7a816081f4587e82aa79686407e347d5718b2d41305f61ace64ad6fac48d

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pymorphy2
    - python

test:
  imports:
    - yargy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/natasha/yargy
  summary: Rule-based facts extraction for Russian language
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - harri-pltr
